In [10]:
import numpy as np

In [4]:
import torch

In [5]:
x=torch.tensor(3.0,requires_grad=True)
w=torch.tensor(4.,requires_grad=True) # for automatic grdiants
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3., requires_grad=True),
 tensor(4., requires_grad=True),
 tensor(5., requires_grad=True))

In [6]:
y=x*w+b
y

tensor(17., grad_fn=<AddBackward0>)

In [7]:
y.backward()

In [8]:
print('dy/dx',x.grad) 
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx tensor(4.)
dy/dw tensor(3.)
dy/db tensor(1.)


In [11]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [12]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [13]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print("Inputs:\n",inputs)
print("Targets:\n",targets)

Inputs:
 tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
Targets:
 tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


apple =w11*T11 +w12*r12+w13*r13
orr =w21*T21 +w22*r22+w23*r23

In [15]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 1.3823,  0.1682, -1.4737],
        [-1.5629,  1.3266, -0.7135]], requires_grad=True)
tensor([ 0.1065, -1.9073], requires_grad=True)


In [21]:
def model(x):
    return x @ w.t() + b

In [22]:
model(inputs )

tensor([[  48.9200,  -57.7967],
        [  46.3879,  -73.0536],
        [  57.4400,   -1.4951],
        [  93.8108, -130.6798],
        [   8.4812,  -32.3373]], grad_fn=<AddBackward0>)